[workspace]
resolver = "2"
members = ["git-tui-core", "git-tui", "bench"]

[workspace.package]
version = "0.2.1"
edition = "2021"
license = "MIT"
rust-version = "1.88"
repository = "https://github.com/DevarshVasani/activegit"

[profile.release]
lto = true
strip = true

# The profile that 'dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"
